### ISSUE TITLE
Design first pointer-based mutable data structure in a CNF

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/cnf-mutable-tests#1]
After the simple unboxed-vector-in-CNF works, next step will be something that is still simple but pointer-based (though not threadsafe), for example, a linked list of Ints:

 * root of the structure would be a CNFRef pointing at the first cons cell in the list (and optionally the last as well).
 * each car field would be an unboxed vector of Ints. This could be a singleton vector at first.
 * cdr fields would be mutable pointers to the next cons cell
 * the root would also contain a pointer to a free list as well as a head of the actual list.

This should be enough to implement a traditional imperative sequence structure, with its own memory management scheme.

 * Extending the list would mean mutating the last CDR pointer to point to a new cell, drawn from the freelist if possible, or added to the compact with appendCompact.
 * Popping the first thing off the list would mutate the root's first pointer and extend the freelist.
This structure only grows, never shrinks. Though there could always be a data-structure specific policy to recompact if the freelist grows bigger than the main list by some factor....

**Comment by vikraman** [comment]
Working version with freeList, now on master.

**Comment by rrnewton** [comment]
Great!  So no segfaults presently?

**Comment by vikraman** [comment]
Nope, the tests are running successfully on travis as well.
